### ISSUE TITLE
services list throws error with sh

### ISSUE THREAD

**Issue by AxelanderK** [tunix/digitalocean-dyndns#13]
Hi,

Seems like the last commit has an issue with services list due to sh not supporting this functionality. Changing Line 1 from /bin/sh to bin/bash solves this issue.

https://github.com/tunix/digitalocean-dyndns/blob/688a19663eac7112cc84cf398d97475035f184bc/dyndns.sh#L6L9

**Comment by tunix** [comment]
Merged, thank you!
