### ISSUE TITLE
helm chart for this

### ISSUE THREAD

**Issue by billimek** [tunix/digitalocean-dyndns#2]
FYI, I made this into a helm chart in case you are interested: 

https://github.com/billimek/billimek-charts/tree/master/digitalocean-dyndns

**Comment by tunix** [comment]
Hi @billimek ,

Actually I don't have much expertise with Kubernetes so this is the first time I get to know about helm charts. (weird name btw) 😄 

Your repo seems to be complimentary which gets part of the code from this repo, am I correct? This repo is only for building the Docker image and yours create a helm chart package from it.

I think this repo is as lean as it can be but if you propose a lean way of building both in the same repo, I may consider it.

Thanks for letting me know, it's great to see this repo is useful!

**Comment by billimek** [comment]
Hi @tunix, typically it appears that helm charts (and their associated deployment repos) are separate from the repos that are used to build the underlying docker images.

In this case, after checking with the official helm chart repo maintainers, I'm going to try to get this one added as an official helm chart over at https://github.com/kubernetes/charts
