### ISSUE TITLE
Getting no a record for domain

### ISSUE THREAD

**Issue by thomas126** [tunix/digitalocean-dyndns#7]
Hello guys,

love the work here. Somehow I am getting error all over the place. I tried the docker image and script on my arm device and resolving in the error: no a record found for domain. But there is an a record set for it. Even deleted the one and recreated it. Any ideas?

Best regards

**Comment by tunix** [comment]
Hi @thomas126,

Many things may have caused this. Possible causes are:

* Invalid DO token
* Domain may not be an A record
* You may have entered an invalid NAME env variable

What is the output of the following command?

```
DIGITALOCEAN_TOKEN="your_do_token"
DOMAIN="yourdomain.com"

curl -s -X GET \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" \
        https://api.digitalocean.com/v2/domains/$DOMAIN/records
```

**Comment by thomas126** [comment]
I am getting a super long output which ends suddenly. Is it possible I have too many entries and that is the reason why it cannot find the last added one? I have about 20 entries.
Token is valid for sure. A record set aswell and correct domain...

**Comment by thomas126** [comment]
I can confirm trying another domain works fine. I did a workaround with a cname renters. Still is there a way to make larger entry’s per domain possible?

**Comment by tunix** [comment]
@thomas126 Would you mind sharing the entries as I have no clue for where the problem lies.

**Comment by thomas126** [comment]
It’s the number of entries that is causing the problem. I have a Mailserver setup. So there are a lot of entries. Some TXT and so on. Seems like half of the entries of That Domain are not being read out because of this. I can share the output later when I am home...

**Comment by tunix** [comment]
@thomas126 - there is currently an open PR which wants to bring pagination support but its owner haven't responded to my comment yet. Would you consider improving it?
